project:
  type: website

website:
  title: "Régis Gourdel"
  page-footer: "Copyright 2023, Régis Gourdel. Photo credit: Sânziana Perju."
  site-url: https://regisgourdel.github.io/
  search: false
  favicon: owl_3d.png
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      light: simplex
      dark: cyborg
    css: styles.css
    toc: true
