### Credit and climate sentiments: the decarbonization frontier of risk pricing (2024)

###### Full citation:

```{python}
#| echo: false
#| output: asis
citation_print("credit_sentiments")
```

###### Abstract:

The role of banks in supporting the low-carbon transition has proved controversial as they have priced climate transition risk but maintained investment in polluting industries.
This paper provides first a theoretical benchmark for the carbon premium, based on a formalization of the concept of climate sentiments, the policy-dependent present value of firms' capital, and the Merton model.
I find that the current empirical evidence for carbon premia matches a reasonable calibration of investment dynamics in productive capital, with a limited space for higher premia even when banks strongly expect future climate-mitigation policies.
Second, I consider discrepancies in climate sentiments between lenders and borrowers, to determine when banks could push reticent borrowers to green their operations, or prevent them from doing so.
I find that variations in the cost of debt due to the carbon premium are generally not enough of a decarbonization incentive alone.
Macro-prudential measures that complement carbon pricing and policies that limit the lending volume would then be necessary to decarbonize the economy further through the financial system.

###### Bibtex entry:

```bibtex
{{< include _papers/credit_sentiments.bib >}}
```

###### Presentations at conferences:

-   2nd European Sustainable Finance PhD Workshop --- University of Augsburg, 2024
-   Annual Meeting of the Austrian Economic Association “Transition to a low carbon economy” --- BOKU University, Vienna, 2024
-   2024 International Symposium on Climate, Finance, and Sustainability (ISCFS-2024) --- Université Dauphine, Paris
-   8th Sustainable and Impact Investments International Conference --- University College Dublin, 2025
    + 🥉 Recipient of the third-best paper award
-   The Second International Conference on the Climate-Macro-Finance Interface: New Environmental Challenges for Monetary, Fiscal, and Macroprudential Policy --- Bayes Business School, London, 2025
-   18th RGS Doctoral Conference in Economics --- TU Dortmund, 2025
-   ZEW Conference on “Ageing and Sustainable Finance” --- Mannheim, 2025
-   CINSC INFINITI conference -- Edinburgh, 2025
-   7th Nordic Annual Environmental and Resource Economics (NAERE) Workshop -- Copenhagen, 2025
