### Derisking the low-carbon transition: investors' reaction to climate policies, decarbonization and distributive effects - _Review of Evolutionary Political Economy_ (2022)

> Monasterolo et al., DOI: [10.1007/s43253-021-00062-3]((https://doi.org/10.1007/s43253-021-00062-3))

###### Abstract:
The role of climate finance policies and instruments in scaling up and derisking low-carbon investments has received growing research attention. However, financial actors’ reaction to climate finance initiatives, and their implications on decarbonization of the economy and on inequality, has not been assessed yet.
Our manuscript contributes to address this knowledge gap by analysing under which conditions government’s climate finance policies and investors’ climate risk adjustment can affect the success of the low-carbon transition and the ability to close the green investment gap.
We further develop the EIRIN Stock-Flow Consistent behavioural model with a financial market, an energy market and investors’ portfolio choice of financial contracts, for the European Union.
First, we study the macroeconomic impacts of government’s green subsidies that can be financed either by introducing an unanticipated carbon tax or by issuing green sovereign bonds.
Then, we assess how investors adjust firms’ risk assessment in reaction to the carbon tax introduction, and how this affects firms’ low-carbon investment decisions.
We find that both a carbon tax and green bonds financing can give rise to trade-offs in terms of decarbonization of the economy (absolute emission reductions), distributive effects and public debt sustainability.
The channels of transmission differ and are policy and instrument specific.
Green subsidies that are financed by green sovereign bonds issuance generate positive spillovers on GDP growth and less distributive effects than a carbon tax.
Nevertheless, due to the relative decoupling of the economy, GDP growth impairs emission reduction efforts.
Finally, investors’ climate risk adjustment helps to smooth this trade-off, contributing to a full decoupling.

###### Suggested bibtex citation:

```bibtex
@article{monasterolo2022derisking,
    title = {Derisking the low-carbon transition: investors' reaction to climate policies, decarbonization and distributive effects},
    author = {Monasterolo, Irene and Dunz, Nepomuk
        and Mazzocchetti, Andrea and Gourdel, Régis},
    journal = {Review of Evolutionary Political Economy},
    volume = 3,
    number = 1,
    pages = {31--71},
    year = 2022,
    publisher = {Springer},
    doi = {10.1007/s43253-021-00062-3}
}
```