### Shock amplification in an interconnected financial system of banks and investment funds - _Journal of Financial Stability_ (2024)

> Sydow et al., DOI: [10.1016/j.jfs.2024.101234]((https://doi.org/10.1016/j.jfs.2024.101234))

Working paper version: [ECB working paper No. 2581](https://www.ecb.europa.eu/pub/pdf/scpwps/ecb.wp2581~63c8ffb7dc.en.pdf)

###### Abstract:
This paper shows how the combined endogenous reaction of banks and investment funds to an exogenous shock can amplify or dampen losses to the financial system compared to results from single-sector stress testing models.
We build a new model of contagion propagation using a very large and granular data set for the euro area. Based on the economic shock caused by the Covid-19 outbreak, we model three sources of exogenous shocks: a default shock, a market shock and a redemption shock.
Our contagion mechanism operates through a dual channel of liquidity and solvency risk.
Our analysis reveals that adding the fund sector to our model for banks leads to additional losses through fire sales and a further depletion of banks’ capital ratios by around one percentage point.
The main driver of additional bank losses are endogenous market losses generated by investment funds’ asset liquidation.

###### Suggested bibtex citation:

```bibtex
@article{sydow2024shock,
    title = {Shock amplification in an interconnected financial system of banks and investment funds},
    journal = {Journal of Financial Stability},
    volume = 71,
    pages = 101234,
    year = 2024,
    issn = {1572-3089},
    doi = {10.1016/j.jfs.2024.101234},
    author = {Sydow, Matthias and Schilte, Aurore and Covi, Giovanni
        and Deipenbrock, Marija and Del Vecchio, Leonardo and Fiedor, Pawel
        and Fukker, Gábor and Gehrend, Max and Gourdel, Régis
        and Grassi, Alberto and Hilberg, Björn and Kaijser, Michiel
        and Kaoudis, Georgios and Mingarelli, Luca and Montagna, Mattia
        and Piquard, Thibaut and Salakhova, Dilyara and Tente, Natalia},
}
```